name: tcc_energia
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pandas
  - numpy
  - pyyaml
  - scikit-learn
  - streamlit
  - plotly
  - folium
  - matplotlib
  - openpyxl
  - pip
  - pip:
      - streamlit-folium
