# Este arquivo é apenas para ambiente local ou instalação manual.
# Para deploy no Streamlit Cloud, utilize apenas requirements.txt.
# NÃO remover dependências daqui para ambiente local, mas sempre teste com pip!
name: tcc_energia
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pandas
  - numpy
  - pyyaml
  - scikit-learn
  - streamlit
  - plotly
  - folium
  - matplotlib
  - openpyxl
  - pip
  - pip:
      - streamlit-folium
